### ISSUE TITLE
Error when testing with sdk 

### ISSUE THREAD

**Issue by ratthapol** [line/line-sdk-starter-ios#2]
I downloaded the project and installed SDK libraries (version 3.1.13).

I configured the Channel ID and URL Scheme the same value as I put in the Technical Configuration on the developer website.

When I tested this application by using "LOGIN with LINE" option, the application brought me to LINE application and let me to allow the access of my profile information. If I choose the allow option, LINE application can redirect me back into application but I got this error.
![img_4085](https://cloud.githubusercontent.com/assets/14066668/10212904/1878c566-6830-11e5-93e3-095f16dc491c.PNG)

I changed to test by using "LOGIN in app" option instead. The Web view came up on the screen and I logged in by using my account.Then, The web view is dismissed from the screen and I got this error.
![img_4086](https://cloud.githubusercontent.com/assets/14066668/10212932/8ad329ee-6830-11e5-93fe-0b004ea1d1fc.PNG)

I don't know about the meaning and what is the cause of these errors. I tried to recheck all of the configuration options in the application but I'm still not sure what is the problem. If you have any information or guiding in these errors, please report back. Thank you.

**Comment by GuitarSucks** [comment]
@ratthapol 
Are you working on iOS9 SDK ? If so please check 
https://developers.line.me/ios/development-with-sdk#settings_ios9

**Comment by helloooideeeeea** [comment]
@GuitarSucks I have also had the same problem.
I downloaded the project and installed SDK libraries (version 3.1.14).

lineAdapter.isAuthorized is never return true.
Output Open url's(NSURL) logs. 
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  NSLog(@"custom url %@",  url.absoluteString);
  return [LineAdapter handleOpenURL:url];
  }

The following contents.

line3rdp.{OUR_CUSTOM_SCHEMA}://authorize/?requestToken=&resultCode=INTERNALERROR&resultMessage=%E6%93%8D%E4%BD%9C%E3%82%92%E5%AE%8C%E4%BA%86%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%9B%E3%82%93%E3%81%A7%E3%81%97%E3%81%9F%E3%80%82%EF%BC%88NLChannelGatewayErrorDomain+%E3%82%A8%E3%83%A9%E3%83%BC+102%E3%80%82%EF%BC%89

Do you know what it is caused by?

**Comment by helloooideeeeea** [comment]
@GuitarSucks I didn't register developer's Line account on LINE Developers site.
I registered developer's Line account. I got response [ login success ].
thanks.

**Comment by GuitarSucks** [comment]
@helloooideeeeea 
Ohh. Good to hear so
